# TCL File Generated by Component Editor 15.0
# Wed Jan 06 15:13:01 CET 2016
# DO NOT MODIFY


# 
# lcd_sys "lcd_sys" v1.0
#  2016.01.06.15:13:01
# 
# 

# 
# request TCL package from ACDS 15.0
# 
package require -exact qsys 15.0


# 
# module lcd_sys
# 
set_module_property DESCRIPTION ""
set_module_property NAME lcd_sys
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME lcd_sys
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL LCD
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file LCD.vhd VHDL PATH ../LCD/quartus/LCD.vhd TOP_LEVEL_FILE
add_fileset_file controller.vhd VHDL PATH ../LCD/quartus/controller.vhd
add_fileset_file fifo.vhd VHDL PATH ../LCD/quartus/fifo.vhd
add_fileset_file master.vhd VHDL PATH ../LCD/quartus/master.vhd
add_fileset_file slave.vhd VHDL PATH ../LCD/quartus/slave.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 as_add address Input 3
add_interface_port avalon_slave_0 as_wait_request waitrequest Output 1
add_interface_port avalon_slave_0 as_wrdata writedata Input 32
add_interface_port avalon_slave_0 as_write write Input 1
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point bus
# 
add_interface bus avalon start
set_interface_property bus addressUnits SYMBOLS
set_interface_property bus associatedClock clock
set_interface_property bus associatedReset reset
set_interface_property bus bitsPerSymbol 8
set_interface_property bus burstOnBurstBoundariesOnly false
set_interface_property bus burstcountUnits WORDS
set_interface_property bus doStreamReads false
set_interface_property bus doStreamWrites false
set_interface_property bus holdTime 0
set_interface_property bus linewrapBursts false
set_interface_property bus maximumPendingReadTransactions 0
set_interface_property bus maximumPendingWriteTransactions 0
set_interface_property bus readLatency 0
set_interface_property bus readWaitTime 1
set_interface_property bus setupTime 0
set_interface_property bus timingUnits Cycles
set_interface_property bus writeWaitTime 0
set_interface_property bus ENABLED true
set_interface_property bus EXPORT_OF ""
set_interface_property bus PORT_NAME_MAP ""
set_interface_property bus CMSIS_SVD_VARIABLES ""
set_interface_property bus SVD_ADDRESS_GROUP ""

add_interface_port bus bus_read_data_valid readdatavalid Input 1
add_interface_port bus bus_waitReq waitrequest Input 1
add_interface_port bus bus_read_data readdata Input 16
add_interface_port bus bus_read read Output 1
add_interface_port bus bus_add address Output 32
add_interface_port bus bus_BE byteenable Output 2
add_interface_port bus bus_burstCount burstcount Output 8


# 
# connection point lcd_conduit
# 
add_interface lcd_conduit conduit end
set_interface_property lcd_conduit associatedClock clock
set_interface_property lcd_conduit associatedReset ""
set_interface_property lcd_conduit ENABLED true
set_interface_property lcd_conduit EXPORT_OF ""
set_interface_property lcd_conduit PORT_NAME_MAP ""
set_interface_property lcd_conduit CMSIS_SVD_VARIABLES ""
set_interface_property lcd_conduit SVD_ADDRESS_GROUP ""

add_interface_port lcd_conduit lcd_data lcd_data Output 16
add_interface_port lcd_conduit lcd_dc lcd_dc Output 1
add_interface_port lcd_conduit lcd_rd lcd_rd Output 1
add_interface_port lcd_conduit lcd_wr lcd_wr Output 1
add_interface_port lcd_conduit lcd_reset_n lcd_reset_n Output 1


# 
# connection point camera_interface
# 
add_interface camera_interface conduit end
set_interface_property camera_interface associatedClock ""
set_interface_property camera_interface associatedReset ""
set_interface_property camera_interface ENABLED true
set_interface_property camera_interface EXPORT_OF ""
set_interface_property camera_interface PORT_NAME_MAP ""
set_interface_property camera_interface CMSIS_SVD_VARIABLES ""
set_interface_property camera_interface SVD_ADDRESS_GROUP ""

add_interface_port camera_interface ext_IRQ ext_irq Input 1
add_interface_port camera_interface am_readOK am_readok Output 1

