#ifndef __CMOS_SENSOR_OUTPUT_GENERATOR_REGS_H__
#define __CMOS_SENSOR_OUTPUT_GENERATOR_REGS_H__

#if defined(__KERNEL__) || defined(MODULE)
#include <linux/types.h>
#else
#include <stdint.h>
#endif

#include "cmos_sensor_output_generator_io.h"

/* All registers are 32 bits wide */

#define CMOS_SENSOR_OUTPUT_GENERATOR_CONFIG_ROW_SIZE_OFST                           (0 * 4) /* RW */
#define CMOS_SENSOR_OUTPUT_GENERATOR_CONFIG_COL_SIZE_OFST                           (1 * 4) /* RW */
#define CMOS_SENSOR_OUTPUT_GENERATOR_CONFIG_FRAME_FRAME_BLANK_CYCLES_OFST           (2 * 4) /* RW */
#define CMOS_SENSOR_OUTPUT_GENERATOR_CONFIG_FRAME_LINE_BLANK_CYCLES_OFST            (3 * 4) /* RW */
#define CMOS_SENSOR_OUTPUT_GENERATOR_CONFIG_LINE_LINE_BLANK_CYCLES_OFST             (4 * 4) /* RW */
#define CMOS_SENSOR_OUTPUT_GENERATOR_CONFIG_LINE_FRAME_BLANK_CYCLES_OFST            (5 * 4) /* RW */
#define CMOS_SENSOR_OUTPUT_GENERATOR_CONFIG_RANDOM_OFST                             (6 * 4) /* RW */
#define CMOS_SENSOR_OUTPUT_GENERATOR_COMMAND_OFST                                   (7 * 4) /* WO */

#define CMOS_SENSOR_OUTPUT_GENERATOR_CONFIG_ROW_SIZE_ADDR(base)                     ((void *) ((uint8_t *) (base) + CMOS_SENSOR_OUTPUT_GENERATOR_CONFIG_ROW_SIZE_OFST))
#define CMOS_SENSOR_OUTPUT_GENERATOR_CONFIG_COL_SIZE_ADDR(base)                     ((void *) ((uint8_t *) (base) + CMOS_SENSOR_OUTPUT_GENERATOR_CONFIG_COL_SIZE_OFST))
#define CMOS_SENSOR_OUTPUT_GENERATOR_CONFIG_FRAME_FRAME_BLANK_CYCLES_ADDR(base)     ((void *) ((uint8_t *) (base) + CMOS_SENSOR_OUTPUT_GENERATOR_CONFIG_FRAME_FRAME_BLANK_CYCLES_OFST))
#define CMOS_SENSOR_OUTPUT_GENERATOR_CONFIG_FRAME_LINE_BLANK_CYCLES_ADDR(base)      ((void *) ((uint8_t *) (base) + CMOS_SENSOR_OUTPUT_GENERATOR_CONFIG_FRAME_LINE_BLANK_CYCLES_OFST))
#define CMOS_SENSOR_OUTPUT_GENERATOR_CONFIG_LINE_LINE_BLANK_CYCLES_ADDR(base)       ((void *) ((uint8_t *) (base) + CMOS_SENSOR_OUTPUT_GENERATOR_CONFIG_LINE_LINE_BLANK_CYCLES_OFST))
#define CMOS_SENSOR_OUTPUT_GENERATOR_CONFIG_LINE_FRAME_BLANK_CYCLES_ADDR(base)      ((void *) ((uint8_t *) (base) + CMOS_SENSOR_OUTPUT_GENERATOR_CONFIG_LINE_FRAME_BLANK_CYCLES_OFST))
#define CMOS_SENSOR_OUTPUT_GENERATOR_CONFIG_RANDOM_ADDR(base)                       ((void *) ((uint8_t *) (base) + CMOS_SENSOR_OUTPUT_GENERATOR_CONFIG_RANDOM_OFST))
#define CMOS_SENSOR_OUTPUT_GENERATOR_COMMAND_ADDR(base)                             ((void *) ((uint8_t *) (base) + CMOS_SENSOR_OUTPUT_GENERATOR_COMMAND_OFST))

#define CMOS_SENSOR_OUTPUT_GENERATOR_CONFIG_SEQUENTIAL                              (0)
#define CMOS_SENSOR_OUTPUT_GENERATOR_CONFIG_RANDOM                                  (1)
#define CMOS_SENSOR_OUTPUT_GENERATOR_COMMAND_STOP                                   (0)
#define CMOS_SENSOR_OUTPUT_GENERATOR_COMMAND_START                                  (1)

#define CMOS_SENSOR_OUTPUT_GENERATOR_CONFIG_ROW_SIZE_MIN                            (1)
#define CMOS_SENSOR_OUTPUT_GENERATOR_CONFIG_COL_SIZE_MIN                            (1)
#define CMOS_SENSOR_OUTPUT_GENERATOR_CONFIG_FRAME_FRAME_BLANK_CYCLES_MIN            (1)
#define CMOS_SENSOR_OUTPUT_GENERATOR_CONFIG_FRAME_LINE_BLANK_CYCLES_MIN             (0)
#define CMOS_SENSOR_OUTPUT_GENERATOR_CONFIG_LINE_LINE_BLANK_CYCLES_MIN              (1)
#define CMOS_SENSOR_OUTPUT_GENERATOR_CONFIG_LINE_FRAME_BLANK_CYCLES_MIN             (0)

#define CMOS_SENSOR_OUTPUT_GENERATOR_CONFIG_ROW_SIZE_MAX                            (2147483647)
#define CMOS_SENSOR_OUTPUT_GENERATOR_CONFIG_COL_SIZE_MAX                            (2147483647)
#define CMOS_SENSOR_OUTPUT_GENERATOR_CONFIG_FRAME_FRAME_BLANK_CYCLES_MAX            (2147483647)
#define CMOS_SENSOR_OUTPUT_GENERATOR_CONFIG_FRAME_LINE_BLANK_CYCLES_MAX             (2147483647)
#define CMOS_SENSOR_OUTPUT_GENERATOR_CONFIG_LINE_LINE_BLANK_CYCLES_MAX              (2147483647)
#define CMOS_SENSOR_OUTPUT_GENERATOR_CONFIG_LINE_FRAME_BLANK_CYCLES_MAX             (2147483647)

#define CMOS_SENSOR_OUTPUT_GENERATOR_WR_CONFIG_ROW_SIZE(base, data)                 cmos_sensor_output_generator_write_word(CMOS_SENSOR_OUTPUT_GENERATOR_CONFIG_ROW_SIZE_ADDR((base)), (data))
#define CMOS_SENSOR_OUTPUT_GENERATOR_WR_CONFIG_COL_SIZE(base, data)                 cmos_sensor_output_generator_write_word(CMOS_SENSOR_OUTPUT_GENERATOR_CONFIG_COL_SIZE_ADDR((base)), (data))
#define CMOS_SENSOR_OUTPUT_GENERATOR_WR_CONFIG_FRAME_FRAME_BLANK_CYCLES(base, data) cmos_sensor_output_generator_write_word(CMOS_SENSOR_OUTPUT_GENERATOR_CONFIG_FRAME_FRAME_BLANK_CYCLES_ADDR((base)), (data))
#define CMOS_SENSOR_OUTPUT_GENERATOR_WR_CONFIG_FRAME_LINE_BLANK_CYCLES(base, data)  cmos_sensor_output_generator_write_word(CMOS_SENSOR_OUTPUT_GENERATOR_CONFIG_FRAME_LINE_BLANK_CYCLES_ADDR((base)), (data))
#define CMOS_SENSOR_OUTPUT_GENERATOR_WR_CONFIG_LINE_LINE_BLANK_CYCLES(base, data)   cmos_sensor_output_generator_write_word(CMOS_SENSOR_OUTPUT_GENERATOR_CONFIG_LINE_LINE_BLANK_CYCLES_ADDR((base)), (data))
#define CMOS_SENSOR_OUTPUT_GENERATOR_WR_CONFIG_LINE_FRAME_BLANK_CYCLES(base, data)  cmos_sensor_output_generator_write_word(CMOS_SENSOR_OUTPUT_GENERATOR_CONFIG_LINE_FRAME_BLANK_CYCLES_ADDR((base)), (data))
#define CMOS_SENSOR_OUTPUT_GENERATOR_WR_CONFIG_RANDOM(base, data)                   cmos_sensor_output_generator_write_word(CMOS_SENSOR_OUTPUT_GENERATOR_CONFIG_RANDOM_ADDR((base)), (data))
#define CMOS_SENSOR_OUTPUT_GENERATOR_WR_COMMAND(base, data)                         cmos_sensor_output_generator_write_word(CMOS_SENSOR_OUTPUT_GENERATOR_COMMAND_ADDR((base)), (data))
#define CMOS_SENSOR_OUTPUT_GENERATOR_RD_CONFIG_ROW_SIZE(base)                       cmos_sensor_output_generator_read_word(CMOS_SENSOR_OUTPUT_GENERATOR_CONFIG_ROW_SIZE_ADDR((base)))
#define CMOS_SENSOR_OUTPUT_GENERATOR_RD_CONFIG_COL_SIZE(base)                       cmos_sensor_output_generator_read_word(CMOS_SENSOR_OUTPUT_GENERATOR_CONFIG_COL_SIZE_ADDR((base)))
#define CMOS_SENSOR_OUTPUT_GENERATOR_RD_CONFIG_FRAME_FRAME_BLANK_CYCLES(base)       cmos_sensor_output_generator_read_word(CMOS_SENSOR_OUTPUT_GENERATOR_CONFIG_FRAME_FRAME_BLANK_CYCLES_ADDR((base)))
#define CMOS_SENSOR_OUTPUT_GENERATOR_RD_CONFIG_FRAME_LINE_BLANK_CYCLES(base)        cmos_sensor_output_generator_read_word(CMOS_SENSOR_OUTPUT_GENERATOR_CONFIG_FRAME_LINE_BLANK_CYCLES_ADDR((base)))
#define CMOS_SENSOR_OUTPUT_GENERATOR_RD_CONFIG_LINE_LINE_BLANK_CYCLES(base)         cmos_sensor_output_generator_read_word(CMOS_SENSOR_OUTPUT_GENERATOR_CONFIG_LINE_LINE_BLANK_CYCLES_ADDR((base)))
#define CMOS_SENSOR_OUTPUT_GENERATOR_RD_CONFIG_LINE_FRAME_BLANK_CYCLES(base)        cmos_sensor_output_generator_read_word(CMOS_SENSOR_OUTPUT_GENERATOR_CONFIG_LINE_FRAME_BLANK_CYCLES_ADDR((base)))
#define CMOS_SENSOR_OUTPUT_GENERATOR_RD_CONFIG_RANDOM(base)                         cmos_sensor_output_generator_read_word(CMOS_SENSOR_OUTPUT_GENERATOR_CONFIG_RANDOM_ADDR((base)))

#endif /* __CMOS_SENSOR_OUTPUT_GENERATOR_REGS_H__ */
